baseurl = "http://nanairo1.github.io/hugoblog"
languageCode = "ja-jp"
title = "ShihoShoshi Matsumiya"
theme = "hyde"
canonifyurls = true

[params]
  description = "This is yourblog"
  author = "your name"

[taxonomies]
  category = "categories"
  tag = "tags"
